create table rp1fa2025.conferences (
  name text not null,
  constraint conferences_pkey primary key (name),
) TABLESPACE pg_default;

create table rp1fa2025.papers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  subtitle text null,
  students text not null,
  conference text not null,
  constraint papers_pkey primary key (id),
  constraint papers_students_key unique (students),
  constraint papers_title_key unique (title),
  constraint papers_conference_fkey foreign KEY (conference) references rp1fa2025.conferences (name)
) TABLESPACE pg_default;